[package]
name = "foreignc_util"
version = "0.1.0"
authors = ["Martin Pinholt <mapi@itu.dk>"]
edition = "2018"
repository = "https://github.com/mart368b/foreignc"
license-file = "../LICENSE"

[lib]
name = "foreignc_util"
path = "src/lib.rs"